apiVersion: v1
kind: Service
metadata:
  name: chat-web
spec:
  selector:
    app: chat-web  # This matches the label defined in the deployment
  ports:
    - protocol: TCP
      port: 80  # External port for the service
      targetPort: 80  # Port on the container
  type: ClusterIP  # Change to NodePort or LoadBalancer based on your needs (ClusterIP is default)
