apiVersion: v1
kind: Service
metadata:
  name: chat-presence
spec:
  selector:
    app: chat-presence  # Match the label from the Deployment
  ports:
    - name: http-port
      protocol: TCP
      port: 7777  # External port
      targetPort: 7777  # Container's port
  type: ClusterIP  # ClusterIP is used for internal communication, change if external access is needed