apiVersion: v1
kind: Service
metadata:
  name: chat-sd
spec:
  selector:
    app: chat-sd  # This matches the label defined in the deployment
  ports:
    - protocol: TCP
      port: 8888  # External port for the service
      targetPort: 8888  # Port on the container
  type: ClusterIP  # ClusterIP exposes the service on an internal IP within the cluster
