apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus-ds
    type: prometheus
    access: proxy
    url: ${PROMETHEUS_URL}
    isDefault: true
    jsonData:
      timeInterval: "15s"
    editable: true