apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-messages
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-messages
  template:
    metadata:
      labels:
        app: chat-messages
    spec:
      containers:
        - name: chat-messages
          image: dedder98/chat-messages
          ports:
            - containerPort: 5678
          env:
            - name: FRONTEND_URL
              value: "http://localhost:3000"
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq"
            - name: CASSANDRA_POINT
              value: "cassandra"
