apiVersion: v1
kind: Service
metadata:
  name: chat-messages
spec:
  selector:
    app: chat-messages  # This matches the label defined in the deployment
  ports:
    - protocol: TCP
      port: 5678  # External port for the service
      targetPort: 5678  # Port on the container
  type: ClusterIP  # ClusterIP exposes the service on an internal IP within the cluster