apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-container
  template:
    metadata:
      labels:
        app: redis-container
    spec:
      containers:
        - name: redis-container
          image: redis:latest
          ports:
            - containerPort: 6379  # Redis port
