apiVersion: v1
kind: Service
metadata:
  name: redis-container
spec:
  selector:
    app: redis-container  # This matches the label defined in the deployment
  ports:
    - name: redis-port  # Name for the Redis port (6379)
      protocol: TCP
      port: 6379  # External port for Redis
      targetPort: 6379  # Port on the container
  type: ClusterIP  # ClusterIP exposes the service on an internal IP within the cluster