apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq  # This matches the label defined in the deployment
  ports:
    - name: amqp-port  # Name for AMQP port (5672)
      protocol: TCP
      port: 5672  # External port for AMQP
      targetPort: 5672  # Port on the container
    - name: management-port  # Name for RabbitMQ Management UI port (15672)
      protocol: TCP
      port: 15672  # External port for management UI
      targetPort: 15672  # Port on the container
  type: ClusterIP  # ClusterIP exposes the service on an internal IP within the cluster
