apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      terminationGracePeriodSeconds: 500
      containers:
        - name: cassandra
          image: cassandra:latest
          ports:
            - containerPort: 9042  # CQL port
            - containerPort: 9160  # Thrift port
          resources:
            limits:
              cpu: "500m"
              memory: 1Gi
            requests:
              cpu: "500m"
          env:
            - name: CASSANDRA_USER
              value: "admin"
            - name: CASSANDRA_PASSWORD
              value: "admin"
            - name: MAX_HEAP_SIZE
              value: 512M
            - name: HEAP_NEWSIZE
              value: 100M
          volumeMounts:
            - name: cassandra-data
              mountPath: /var/lib/cassandra
      volumes:
        - name: cassandra-data
          persistentVolumeClaim:
            claimName: cassandra-data-pvc  # Persistent volume claim for data
