apiVersion: v1
kind: Service
metadata:
  name: cassandra
spec:
  selector:
    app: cassandra  # Matches the label defined in the deployment
  ports:
    - name: cql-port  # Name for the Cassandra CQL port (9042)
      protocol: TCP
      port: 9042  # External port for CQL
      targetPort: 9042  # Port on the container
    - name: thrift-port  # Name for the Cassandra Thrift port (9160)
      protocol: TCP
      port: 9160  # External port for Thrift
      targetPort: 9160  # Port on the container
  type: ClusterIP  # ClusterIP exposes the service on an internal IP within the cluster
