name: Validate and Publish Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker-builds:
    name: Docker Image Build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub (only on push)
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Inject config.js for chat-web
        run: |
          mkdir -p ./chat-web/app/public
          cat <<EOF > ./chat-web/app/public/config.js
          window.VITE_APP_SERVICE_DISCOVERY_URL = "http://localhost:8888";
          window.VITE_APP_MESSAGING_SERVICE_URL = "http://localhost:5678";
          window.VITE_APP_PRESENCE_URL = "http://localhost:7777";
          window.VITE_APP_FEDERATED_GRAPH = "http://localhost:4000";
          window.VITE_APP_ENABLE_GRAPH = "true";
          window.VITE_APP_DISABLE_CHAT_SD = "true";
          window.VITE_APP_WS_URL = "localhost:4321";
          EOF

      - name: Build all Docker images
        run: |
          set -e

          echo "▶ Building chat-sd"
          docker build -t chat-sd ./chat-sd/app -f ./chat-sd/app/Dockerfile

          echo "▶ Building chat-web"
          docker build -t chat-web ./chat-web/app -f ./chat-web/app/Dockerfile

          echo "▶ Building chat-messages"
          docker build -t chat-messages ./chat-messages/app -f ./chat-messages/app/Dockerfile

          echo "▶ Building chat-ws"
          docker build -t chat-ws ./chat-ws/app -f ./chat-ws/app/Dockerfile

          echo "▶ Building chat-presence"
          docker build -t chat-presence ./chat-presence/app -f ./chat-presence/app/Dockerfile

          echo "▶ Building init-cassandra"
          docker build -t init-cassandra ./cassandra -f ./cassandra/init.Dockerfile

      - name: Push images (only on main push)
        if: github.event_name == 'push'
        run: |
          docker tag chat-sd ${{ secrets.DOCKERHUB_USER }}/chat-sd:latest
          docker tag chat-web ${{ secrets.DOCKERHUB_USER }}/chat-web:latest
          docker tag chat-messages ${{ secrets.DOCKERHUB_USER }}/chat-messages:latest
          docker tag chat-ws ${{ secrets.DOCKERHUB_USER }}/chat-ws:latest
          docker tag chat-presence ${{ secrets.DOCKERHUB_USER }}/chat-presence:latest
          docker tag init-cassandra ${{ secrets.DOCKERHUB_USER }}/init-cassandra:latest

          docker push ${{ secrets.DOCKERHUB_USER }}/chat-sd:latest
          docker push ${{ secrets.DOCKERHUB_USER }}/chat-web:latest
          docker push ${{ secrets.DOCKERHUB_USER }}/chat-messages:latest
          docker push ${{ secrets.DOCKERHUB_USER }}/chat-ws:latest
          docker push ${{ secrets.DOCKERHUB_USER }}/chat-presence:latest
          docker push ${{ secrets.DOCKERHUB_USER }}/init-cassandra:latest
